# Generated by Django 4.0.2 on 2026-05-12 20:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5000, verbose_name='Respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=5000, verbose_name='Opción')),
                ('is_answer', models.BooleanField(default=False, verbose_name='Es respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Código')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=10000, verbose_name='Descripción')),
                ('background_color', models.CharField(default='#d9efed', max_length=20, verbose_name='Color de fondo')),
                ('text_color', models.CharField(default='#272124', max_length=20, verbose_name='Color del texto')),
                ('collect_email', models.BooleanField(default=False, verbose_name='Recopilar correo')),
                ('authenticated_responder', models.BooleanField(default=False, verbose_name='Requiere autenticación')),
                ('edit_after_submit', models.BooleanField(default=False, verbose_name='Editar después de enviar')),
                ('confirmation_message', models.CharField(default='Su respuesta ha sido registrada.', max_length=10000, verbose_name='Mensaje de confirmación')),
                ('is_quiz', models.BooleanField(default=False, verbose_name='Es cuestionario')),
                ('allow_view_score', models.BooleanField(default=True, verbose_name='Permitir ver puntaje')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.CharField(max_length=20, verbose_name='Código de respuesta')),
                ('responder_ip', models.CharField(max_length=30, verbose_name='IP del participante')),
                ('responder_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo del participante')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder', to=settings.AUTH_USER_MODEL, verbose_name='Participante')),
                ('response', models.ManyToManyField(related_name='response', to='index.Answer', verbose_name='Respuestas')),
                ('response_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_to', to='index.form', verbose_name='Respuesta al formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000, verbose_name='Pregunta')),
                ('question_type', models.CharField(max_length=20, verbose_name='Tipo de pregunta')),
                ('required', models.BooleanField(default=False, verbose_name='Requerida')),
                ('answer_key', models.CharField(blank=True, max_length=5000, verbose_name='Respuesta correcta')),
                ('score', models.IntegerField(blank=True, default=0, verbose_name='Puntaje')),
                ('feedback', models.CharField(max_length=5000, null=True, verbose_name='Retroalimentación')),
                ('choices', models.ManyToManyField(related_name='choices', to='index.Choices', verbose_name='Opciones')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='index.Questions', verbose_name='Preguntas'),
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Establecimiento')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias del Establecimiento')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.comuna', verbose_name='Comuna')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to', to='index.questions', verbose_name='Respuesta a'),
        ),
        migrations.AddField(
            model_name='user',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='index.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
