# Generated by Django 5.2.14 on 2026-05-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_answer_options_alter_choices_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Es público'),
        ),
    ]
