# Generated by Django 5.2.14 on 2026-05-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_form_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='establecimientos',
            field=models.ManyToManyField(blank=True, to='index.establecimiento', verbose_name='Establecimientos'),
        ),
        migrations.AddField(
            model_name='form',
            name='is_private_to_establecimiento',
            field=models.BooleanField(default=False, verbose_name='Es para establecimiento en especifico'),
        ),
    ]
