# Generated by Django 5.2.14 on 2026-05-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_form_establecimientos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='is_private_to_establecimiento',
        ),
        migrations.AlterField(
            model_name='form',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Está Publicado?'),
        ),
    ]
