# Generated by Django 5.2.14 on 2026-06-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_form_is_private_to_establecimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('dv', models.IntegerField(verbose_name='Dígito Verificador')),
                ('nombre_funcionario', models.CharField(max_length=255, verbose_name='Nombre Funcionario')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('descripcion_planta', models.CharField(max_length=100, verbose_name='Descripción Planta')),
                ('descripcion_calidad_juridica', models.CharField(max_length=100, verbose_name='Descripción Calidad Jurídica')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('descripcion_isapre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción Isapre')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('ley', models.CharField(max_length=50, verbose_name='Ley')),
                ('numero_horas', models.IntegerField(verbose_name='Número horas')),
                ('descripcion_establecimiento', models.CharField(max_length=200, verbose_name='Descripción Establecimiento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('fecha_inicio_contrato', models.DateField(verbose_name='Fecha Inicio Contrato')),
                ('fecha_termino_contrato', models.DateField(verbose_name='Fecha Término Contrato')),
                ('fecha_alejamiento', models.DateField(verbose_name='Fecha Alejamiento')),
                ('transitorio', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], max_length=1, verbose_name='Transitorio')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Importación')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['nombre_funcionario'],
                'indexes': [models.Index(fields=['rut'], name='index_funci_rut_5e2e50_idx'), models.Index(fields=['descripcion_planta'], name='index_funci_descrip_40c070_idx'), models.Index(fields=['fecha_inicio_contrato'], name='index_funci_fecha_i_0fbafa_idx')],
            },
        ),
    ]
