# Generated by Django 5.2.14 on 2026-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dv',
            field=models.CharField(max_length=1, verbose_name='Dígito Verificador'),
        ),
    ]
