# Generated by Django 5.2.14 on 2026-06-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_funcionario_dv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='fecha_alejamiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Alejamiento'),
        ),
    ]
