# Generated by Django 5.2.14 on 2026-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_funcionario_fecha_alejamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='fecha_inicio_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Contrato'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fecha_termino_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Término Contrato'),
        ),
    ]
