# Generated by Django 5.2.14 on 2026-06-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_funcionario_fecha_inicio_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='collect_rut',
            field=models.BooleanField(default=False, verbose_name='Recopilar RUT'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='establecimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.establecimiento', verbose_name='Establecimientos'),
        ),
        migrations.AddField(
            model_name='responses',
            name='responder_rut',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT del participante'),
        ),
    ]
