# Generated by Django 5.2.14 on 2026-06-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_form_collect_rut_funcionario_establecimientos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='index.funcionario', verbose_name='Participante'),
        ),
    ]
