# Generated by Django 5.2.14 on 2026-06-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_responses_responder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='establecimientos',
            new_name='establecimiento',
        ),
    ]
