# Generated by Django 5.2.14 on 2026-06-04 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_rename_establecimientos_funcionario_establecimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expiration_date', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.form')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='FormAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='index.form')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='index.funcionario')),
            ],
            options={
                'verbose_name': 'Autorización de Formulario',
                'verbose_name_plural': 'Autorizaciones de Formularios',
                'unique_together': {('form', 'funcionario')},
            },
        ),
    ]
