# Generated by Django 5.2.14 on 2026-06-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_formtoken_formauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='formauthorization',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Token de uso'),
        ),
    ]
