# Generated by Django 5.2.14 on 2026-06-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_formauthorization_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormAuthorization',
        ),
    ]
