# Generated by Django 5.2.14 on 2026-06-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_delete_formauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Es de prueba'),
        ),
    ]
