# Generated by Django 5.2.14 on 2026-06-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_responses_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='form',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
