# Generated by Django 5.2.14 on 2026-06-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_form_end_date_form_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='collect_token',
            field=models.BooleanField(default=False, verbose_name='Recopilar Token'),
        ),
        migrations.AddField(
            model_name='formtoken',
            name='tokencopy',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Copia del Token'),
        ),
    ]
